version: 2
jobs:
  build:
    working_directory: ~/HanSoloSEG2105/ASAPServices
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: echo "I dont know what to do here"